providers = ["python"]

[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.main:app --bind 0.0.0.0:$PORT"
